name: Deploy to VPS

on:
  push:
    branches:
      - master  # Specify which branch triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_SSH_KEY }}  # Use the secret you added for the SSH key

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@109.199.103.20 '
        cd /root/wanesni.live &&
        git pull origin master &&
        pm2 restart directus
        '
