name: Deploy to VPS

on:
  push:
    branches:
      - master  # Specify which branch triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@109.199.103.20 '
        cd /root/wanesni.live &&
        git pull origin master &&
        pm2 restart directus
        '
