name: Deploy to VPS

on:
  push:
    branches:
      - master  # Specify the branch that triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Deploy to VPS using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/wanesni_app || exit 1
          git pull origin master || exit 1
          npm install || exit 1
          pm2 restart directus || exit 1
          pm2 logs directus
