name: Deploy to VPS

on:
  push:
    branches:
      - master  # Specify the branch that triggers the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Deploy to VPS using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_IP }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          echo "Navigating to the project directory..."
          cd /root/wanesni_app || { echo "Failed to change directory"; exit 1; }

          echo "Pulling the latest code from the master branch..."
          git pull origin master || { echo "Failed to pull from Git repository"; exit 1; }
          
          echo "Restarting the Directus instance with PM2..."
          pm2 restart directus || { echo "Failed to restart PM2 process"; exit 1; }
